#!/usr/bin/perl
use HTTP::Request;
use LWP::UserAgent;
use Time::Piece;
open (MYFILE, '>>Shell.gr.log');
my $t = localtime;


# or for GMT formatted appropriately for your locale:
print MYFILE "=======================| $t |======================= \n";

system('cls');
system(' Title [SK] Shell Grabber V1.0 ');
system "color a";

print"\n";
print "\t _______ __          __ __  _______            __    __               \n";
print "\t|   _   |  |--.-----|  |  ||   _   .----.---.-|  |--|  |--.-----.----.\n";
print "\t|   |___|     |  -__|  |  ||.  |___|   _|  _  |  _  |  _  |  -__|   _|\n";
print "\t|____   |__|__|_____|__|__||.  |   |__| |___._|_____|_____|_____|__|  \n";
print "\t|:  |   |                  |:  |   |                                  \n";     
print "\t|::.. . |                  |::.SK. |                                  \n";
print "\t`-------                   `-------        \n";
print "\t              By Salah Kai wWw.FB.com/SalahKai\n";
print "\n";
print "  [Note: report saved in Shell.gr.log] \n  [Note: If all result say [+] Found maybe it Error !] \n  [Note: First Scan Is For test#]\n\n";
print "\n Enter Site To Scan From Shell \n\n Example: www.site.com \n ==> ";
$site=<STDIN>;
chomp $site;
if($site !~ /http:\/\//) { $site = "http://$site/"; };

print "\n";
########=> how to add new link : set ' ', in a new line and in space set the name or link  ... exp: 'shell.php', <=########
@path = (
'',#Test
'WSO.php',
'sert.php',
'hacker.php',
'sat.php',
'Jijle3.php',
'sitemap.php',
'spofer.php',
'noob.php',
'dz.php',
'1337w0rm.php',
'21.php',
'1177.php',
'1962.php',
'w.php',
'private.php',
'mad.php',
'Mailer-priv8.php',
'mw.php',
'css.php',
'bobox.php',
'cccc.php',
'sexy.php',
'maillist.php',
'mass.d.php',
'w.php',
'shell.php',
'cl.php',
'cpanel.php',
'cpn.php',
'xXx-ID.php',
'sami.php',
'pro.php',
'KURDISHSNIPER97.php',
'D3vil.php',
'Ahmed.php',
'ssss.php',
'rootdzz.php',
'mpc.php',
'meeee.php',
'google.php',
'ex.php',
'&é.php',
'admin5464532.php',
'ad.php',
'dar',
'ss.php',
's.php',
'1998.php',
'wso2.5.php',
'smtp.php',
'wso2.8.php',
'0569386623.php',
'wso000.php',
'wso1.0.php',
'wso781998.php',
'njing.php',
'Ahmed123.php',
'av.php',
'check.php',
'def.php',
'sql.php',
'mysql.php',
'config.php',
'configuration.php',
'madspot.php',
'mailer.php',
'Cgishell.pl',
'ms2.php',
'killer.php',
'fuaad.php',
'changeall.php',
'2.php',
'Sh3ll.php',
'dz0.php',
'dam.php',
'cfg.php',
'back2.php',
'SecCrewz.php',
'user.php',
'cron.php',
'dom.php',
'whmcs.php',
'r00t.php',
'1.php',
'a.php',
'r0k.php',
'abc.php',
'egy.php',
'syrian_shell.php',
'xxx.php',
'settings.php',
'tmp.php',
'cyber.php',
'c99.php',
'r57.php',
'404.php',
'gaza.php',
'1.php',
'd4rk.php',
'index1.php',
'nkr.php',
'xd.php',
'M4r0c.php',
'Dz.php',
'sniper.php',
'ksa.php',
'v4team.php',
'offline.php',
'priv8.php',
'911.php',
'madspotshell.php',
'c100.php',
'sym.php',
'cp.php',
'sa.php',
'readme.php',
'tmp/readme.php',
'wp.zip'.
'd0mains.php',
'madspotshell.php',
'info.php',
'egyshell.php',
'Sym.php',
'c22.php',
'c100.php',
'configuration.php',
'g.php',
'xx.pl',
'ls.php',
'Cpanel.php',
'k.php',
'zone-h.php',
'L3b.php',
'd.php',
'tmp/d.php',
'tmp/L3b.php',
'sado.php',
'admin1.php',
'upload.php',
'up.php',
'vb.zip',
'vb.rar',
'admin2.asp',
'uploads.php',
'sa.php',
'sysadmins/',
'admin1/',
'sniper.php',
'images/Sym.php',
'/r57.php',
'gzaa_spysl',
'sql-new.php',
'/shell.php',
'/sa.php',
'/admin.php',
'/sa2.php',
'/2.php',
'/gaza.php',
'up.php',
'/upload.php',
'/uploads.php',
'shell.php',
'/amad.php',
'/t00.php',
'/dz.php',
'13.php',
'/site.rar',
'/Black.php',
'/site.tar.gz',
'/home.zip',
'/home.rar',
'/home.tar',
'/home.tar.gz',
'/forum.zip',
'/forum.rar',
'/forum.tar',
'/forum.tar.gz',
'/test.txt',
'/ftp.txt',
'/user.txt',
'/site.txt',
'/error_log',
'/error',
'/cpanel',
'/awstats'
,'/site.sql',
'/vb.sql',
'/forum.sql',
'r00t-s3c.php',
'c.php',
'/backup.sql',
'/back.sql',
'/data.sql',
'wp.rar/',
'asp.aspx',
'tmp/vaga.php',
'tmp/killer.php',
'whmcs.php',
'abuhlail.php',
'tmp/killer.php',
'tmp/domaine.pl',
'tmp/domaine.php',
'useradmin/',
'tmp/d0maine.php',
'd0maine.php',
'tmp/sql.php',
'X.php',
'123.php',
'm.php',
'b.php',
'up.php',
'tmp/dz1.php',
'dz1.php',
'forum.zip',
'Symlink.php',
'Symlink.pl',
'forum.rar',
'joomla.zip',
'joomla.rar',
'wp.php',
'buck.sql',
'sysadmin.php',
'images/c99.php',
'xd.php',
'c100.php',
'spy.aspx',
'xd.php',
'tmp/xd.php',
'sym/root/home/',
'billing/killer.php',
'tmp/upload.php',
'tmp/admin.php',
'Server.php',
'tmp/uploads.php',
'tmp/up.php',
'Server/',
'wp-admin/c99.php',
'tmp/priv8.php',
'priv8.php',
'cgi.pl/',
'tmp/cgi.pl',
'dom.php',
'webadmin.html',
'admins.php','bluff.php',
'king.jeen',
'admins/',
'admins.asp',
'admins.php',
'wp.zip',
'1.php',
'2.php',
'3.php',
'4.php',
'5.php',
'6.php',
'7.php',
'8.php',
'9.php',
'10.php',
'a.php',
'z.php',
'e.php',
'r.php',
't.php',
'y.php',
'u.php',
'i.php',
'o.php',
'p.php',
'q.php',
's.php',
'd.php',
'f.php',
'g.php',
'h.php',
'j.php',
'k.php',
'l.php',
'm.php',
'w.php',
'x.php',
'c.php',
'v.php',
'b.php',
'n.php',
'1.php',
'2.php',
'3.php',
'4.php',
'5.php',
'6.php',
'7.php',
'8.php',
'9.php',
'10.php',
'12.php',
'11.php',
'1234.php',
'123456789.php',);

foreach $myshell(@path){

$url = $site.$myshell;
$req = HTTP::Request->new(GET=>$url);
$useragent = LWP::UserAgent->new();

$response = $useragent->request($req);

if ($response->is_success){
system "color C";
 print  "====> Shell Found [+] : $url\n";
open (MYFILE, '>>Shell.gr.log'); 
print MYFILE "===>> Shell Found in .::| $url \n";
}else{
system "color a";
 print  "NotFound [-] : $myshell\n";
}
}